config/routes.rb
StackOverflow::Application.routes.draw do
root :to => 'questions#index'

get "questions/new"
get "sessions/new"
get 'signup', to: 'users#new', as: 'signup'
get 'login', to: 'sessions#new', as: 'login'
get 'logout', to: 'sessions#destroy', as: 'logout'

resources :questions
resources :users
resources :sessions

end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, presence: true
  has_many :questions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    helper_method :current_user

    def authorize
      redirect_to login_url, alert: "Not authorized" if current_user.nil?
    end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

before_filter :authorize, only: [:edit, :update]

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to question_path(@question)
    else
      flash[:alert] = "New question not created."
      render 'new'
    end

    def show
      @question = Question.find(params[:id])
    end

    def edit
      @question = Question.find(params[:id])
    end

    def update
      @question - Question.find(params[:id])
      if @question.update(question_params)
        redirect_to question_path(@question)
      else
        flash[:alert] = "Question #{@question} did not update. Try again!"
        render 'edit'
      end
    end

    def destroy
      @question = Question.find(params[:id])
      @question.destroy
      flash[:alert] = "#{question.title} deleted!"
      redirect_to root_url
    end

    private

    def question_params
      params.require(:question).permit(:title, :content, :user_id)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_username(params[:username])
    if user && user.authenticate(params[:password])
      session[:id] = user.id
      # binding.pry
      redirect_to root_url
    else
      flash.now.alert = "Username or password is invalid."
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    # @user = User.create!(params[:user])
    # respond_to do |format|
    #     format.html { redirect_to root_url }
    #     format.js
    #   end
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :username, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>

  <ul>
    <% object.errors.full_messages_each do |message| %>
      <li><%= message %> </li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tara Overflow</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <div id="user_header">
      <% if current_user %>
       <% binding.pry %>
        Logged in as <%= current_user.username %>
        <%= link_to "Log Out", logout_path %>
      <% else %>
        <%= link_to "Sign Up", signup_path %> or
        <%= link_to "Log In", login_path %>
      <% end %>
    </div>

    <%= flash[:notice] %>
    <%= flash[:alert] %>

<%= yield %>

  </div>
</body>
</html>

app/views/questions/_form.html.erb
<%= render("layouts/errors", :object => @question) %>

<%= form_for @question, :url => question_path, :html => { :multipart => true } do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/questions/index.html.erb
<h1><img src="/assets/stackoverflow_design.png">Tara Overflow</h1>

<ul>
<% @questions.each do |question| %>
  <li><%= link_to question.title, question_path(question) %></li>
  <% end %>
</ul>

<% if current_user != nil %>
  <%= link_to "Add New Question", new_question_path, :class => "btn btn-primary" %>
<% end %>

app/views/questions/new.html.erb
<h1>Ask a New Question</h1>
<%= render 'form' %><br>
<%= link_to 'Main Page', questions_path, :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid.</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.text_field :password_confirmation %>
  </div><br>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>